_BASE_: "Base-cnn.yml"

MODEL:
  META_ARCHITECTURE: Distiller
  BACKBONE:
    NAME: build_resnet_backbone_distill
    DEPTH: 50x
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
  WEIGHTS: projects/LOGS/basemodel/r50/model_best.pth