_BASE_: Base-cnn.yml

MODEL:
  BACKBONE:
    DEPTH: "50x"
    FEAT_DIM: 2048
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: /content/models/lup_moco_r50.pth


OUTPUT_DIR: projects/LOGS/basemodel/r50
