_BASE_: Base-cnn.yml

MODEL:
  BACKBONE:
    DEPTH: "50x"
    FEAT_DIM: 2048
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: /content/models/resnet50_ibn_a-d9d0bb7b.pth


OUTPUT_DIR: /content/drive/MyDrive/Colab Notebooks/Nautilus/projects/LOGS/basemodel/r50
