_BASE_: "Base-sbs-kd.yml"

MODEL:
  BACKBONE:
    DEPTH: 50x
    FEAT_DIM: 2048
    WITH_IBN: True
    PRETRAIN: False
  WEIGHTS: /content/drive/MyDrive/Colab Notebooks/Nautilus/projects/sskd/basemodel/r50-ibn/model_best.pth

KD:
  MODEL_CONFIG: "/content/drive/MyDrive/Colab Notebooks/Nautilus/projects/sskd/basemodel/r101-ibn/config.yaml"
  MODEL_WEIGHTS: "/content/drive/MyDrive/Colab Notebooks/Nautilus/projects/sskd/basemodel/r101-ibn/model_best.pth"

OUTPUT_DIR: "/content/drive/MyDrive/Colab Notebooks/Nautilus/projects/sskd/distiller_r50_101"
